### ISSUE TITLE
Unmounted State Update Warnings

### ISSUE THREAD

**Issue by mpcarolin** [simpleviewinc/sv-mosaic#152]
[dms-ui](https://github.com/simpleviewinc/dms-ui) is encountering a few errors that are complaining about react state updates on unmounted components originating in mosaic.

Steps to reproduce:
1. Using `develop` branch for both `dms-graph` and `dms-ui`, start it up in a **local** kubernetes environment.
2. Visit https://test.local.simpleviewdms.dev/test/grid/
3. Open up the web inspector console
4. Hit the "Create New" button
5. Observe the errors.

I see two errors, one for `DataViewFilterMultiselect` and another for `FilterSingleSelect`, each with the message:

`Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.`

Briefly looking at your components, I see you're calling asynchronously calling `setState` inside of a `useEffect` hook here: 

https://github.com/simpleviewinc/sv-mosaic/blob/ba44d364b6b918b8478ea773854caf2136de5d16/src/components/DataViewFilterMultiselect.jsx#L118-L129

Most likely this is the cause. By the time `setState` executes, the component has already unmounted.

One fix could be to track the mounted state in a ref, clean it up with the useEffect hook, and conditionally run setState:

```ts
function DataViewFilterMultiselect(props) {
  ...
  const isMounted = useRef(false)
  ...
  useEffect(() => {
    isMounted.current = true;
    async function fetchData() { 
 		const selected = await props.args.getSelected(value); 
 		 
 		isMounted.current && setState({ 
 			...state, 
 			selected 
 		}); 
      } 
    ...
    return () => { 
      isMounted.current = false; 
    }
  }, [props.data]);
}
```

**Comment by mpcarolin** [comment]
Full error:

![image](https://user-images.githubusercontent.com/9517356/176325173-3e9a4add-50fa-4ee9-8596-2681003554a5.png)

**Comment by mauriciodeleonc** [comment]
Ticket already closed here: https://simpleviewtools.atlassian.net/browse/MOS-716
